### ISSUE TITLE
'PayFortSDK/PayFortSDK.h' file not found

### ISSUE THREAD

**Issue by snairsumith** [logisticinfotech/react-native-payfort-sdk#1]
When I trying to add in IOS

**Comment by naishadh-logistic** [comment]
@snairsumith install library again and follow steps again. issue fixed.

**Comment by nileshkikani** [comment]
This issue has been close in 1.0.11. Please update library in your code.

**Comment by snairsumith** [comment]
Update to which version? 
I am using version 1.0.11 so still, have an issue . I followed your all steps  
<img width="461" alt="Screen Shot 2020-01-04 at 5 11 40 PM" src="https://user-images.githubusercontent.com/8740519/71765050-a3f85100-2f15-11ea-9037-9ee5ae9cafe8.png">
<img width="749" alt="Screen Shot 2020-01-04 at 4 59 06 PM" src="https://user-images.githubusercontent.com/8740519/71765051-a65aab00-2f15-11ea-99af-97adc1e81dd2.png">
